IN PROGRESS ...

In [7]:
import sys
from underlyings.optimize_portfolio import optimize_portfolio
from underlyings.basket import Basket
import pandas as pd

# Tickers not found to check : GH - WCN - TTE - SGML
basket = Basket(["AAPL","AAPL","TSLA","AMZN"], [ 1 / 3 ] * 4)

#,"AVGO","BA","MDT", "ITW", "ADP","AMZN","NDAQ","BBY","AOS","XOM","YPF","EMR"], )

basket_price_date = pd.to_datetime('2020-01-01')
start_date = pd.to_datetime('2020-01-01')
end_date = pd.to_datetime('2020-01-01')

imply = optimize_portfolio(basket, start_date, end_date) 

UnboundLocalError: cannot access local variable 'resp_dict' where it is not associated with a value

In [2]:
import numpy as np
import scipy as sp
# Get matrices
c = [-8, -12, -22 ,-33]
A = [[17, 27, 34, 4], [12, 33, 15, 4]]
b = [0.1, 0.9]
# define the upper bound and the lower bound
R = (0, None)
T = (0, None)
M = (0, None)
# Implementing the Simplex Algorithm
from scipy.optimize import linprog
# Solve the problem by Simplex method in Optimization
res = linprog(c, A_ub=A, b_ub=b,  bounds=(R, T, M), method='simplex', options={"disp": True})  # linear programming p[roblem
print(res) # print results

ValueError: Invalid input for linprog: unable to interpret bounds with this dimension tuple: (3, 2).

In [15]:
import numpy as np

nb_compo = 4
matrix_vols = [0.05, 0.07, 0.056, 0.033]
vec_returns = [ -0.023, -0.033, -0.04, -0.023] 
I = - np.eye(nb_compo -1)
ones = np.ones(nb_compo -1)
A = np.array([ones, I[0], I[1], I[2], I[0], I[1], I[2], matrix_vols[1: nb_compo]])
# Set the inequality constraints vector
b = np.array([1.0001, -0.001, -0.001, -0.001, 0.2, 0.2, 0.2, matrix_vols[0]])
# Set the coefficients of the linear objective function vector
# Note: when maximizing, change the signs of the c vector coefficient
c = np.array( vec_returns[1:nb_compo])
# Solve linear programming problem
res = linprog(c, A_ub=A, b_ub=b, method='simplex')
# Print results
print('Optimal value:', round(res.fun*-1, ndigits=4),
'\nx values:', res.x,
'\nNumber of iterations performed:', res.nit,
'\nStatus:', res.message)


Optimal value: 0.0357 
x values: [0.001      0.89101786 0.001     ] 
Number of iterations performed: 3 
Status: Optimization terminated successfully.


C:\Users\Administrateur\AppData\Local\Temp\ipykernel_19516\3075230048.py:15: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  res = linprog(c, A_ub=A, b_ub=b, method='simplex')


In [34]:
import numpy as np
from scipy.optimize import minimize


nb_compo = 4
matrix_vols = [0.05, 0.07, 0.056, 0.033]
vec_returns = [ -0.023, -0.033, -0.04, -0.023] 
I = - np.eye(nb_compo -1)
ones = np.ones(nb_compo -1)

A = np.array([I[0], I[1], I[2], ones])
print(A)
# Define the objective function
def objective(x):
    return -np.dot(x, np.dot(A[0:3], x))

# Define the constraint
def constraint(x):
    return x

# Define the bounds
b = np.array([(0.001, 0.7), (0.001, 0.7),(0.001, 0.7),(0.001, 1)])

# Set an initial guess for x
x0 = np.array([0.4, 0.24, 0.24])

# Call the minimize function to solve the optimization problem
res = minimize(objective, x0, method='SLSQP', bounds=b, constraints={'type': 'ineq', 'fun': constraint})

# Print the result
print(res)


[[-1. -0. -0.]
 [-0. -1. -0.]
 [-0. -0. -1.]
 [ 1.  1.  1.]]
 message: Optimization terminated successfully
 success: True
  status: 0
     fun: 3.0000000000002275e-06
       x: [ 1.000e-03  1.000e-03  1.000e-03]
     nit: 2
     jac: [ 2.000e-03  2.000e-03  2.000e-03]
    nfev: 8
    njev: 2


In [4]:
import numpy as np
nb_compo =5

b_components = [0.2323, 1.0001, -0.001] + [-0.001]*(nb_compo-4)
b = np.array(b_components)
b

array([ 2.3230e-01,  1.0001e+00, -1.0000e-03, -1.0000e-03])

In [1]:
import sys

sys.path

['c:\\Users\\Administrateur\\Documents\\MEGA\\IT Quant\\Python\\Notebooks',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\python311.zip',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\Lib',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\DLLs',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311',
 '',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\win32',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\win32\\lib',
 'c:\\Users\\Administrateur\\AppData\\Local\\Programs\\Python\\Python311\\Lib\\site-packages\\Pythonwin',
 'C:\\Users\\Administrateur\\Documents\\MEGA\\IT QUANT\\Python\\underlyings',
 'C:\\Users\\Administrateur\\Documents\\MEGA\\IT QUANT\\Python\\pricing',
 'C:\\Users\\Administrateur\\Do

In [16]:


import numpy as np


A = np.array([1,3,0.5])
B = np.array([[1,3,0.5],[-1,3,0.5],[1,-3,0.5] ])

A
B
C = np.dot(B,A)
C

array([10.25,  8.25, -7.75])